[package]
authors = ["Justin Charette <charetjc@gmail.com>"]
name = "bug-test-01"
version = "0.1.0"

[dependencies]
env_logger = "0.4.3"
error-chain = "0.10.0"
futures = "0.1.14"
log = "0.3.8"
mysql_async = "0.9.3"
tokio-core = "0.1.7"
